### ISSUE TITLE
Rails test fails to run, wrong number of arguments

### ISSUE THREAD

**Issue by dustycoder** [stadia/activerecord-mysql2rgeo-adapter#10]
Running "rails test" results in the error below.  This does not happen when not using the mysql2rgeo adapter. 

Line 40 of mysql2rgeo/schema_statements.rb implements the function `initialize_type_map(m)` and requires 1 argument.  However, the activerecord can call it without an argument.

Line 489 of active_record/connection_adapters/abstract_adapter.rb implements the function as `initialize_type_map(m = type_map)`.  There is a private function that defines `type_map`.

`def type_map
  @type_map ||= Type::TypeMap.new.tap do |mapping|
    initialize_type_map(mapping)
  end
end`

Rails 5.2.0
activerecord-mysql2rgeo-adapter (2.2.0)

**Backtrace**

/var/lib/gems/2.3.0/gems/activerecord-mysql2rgeo-adapter-2.2.0/lib/active_record/connection_adapters/mysql2rgeo/schema_statements.rb:40:in`
`initialize_type_map': wrong number of arguments (given 0, expected 1) (ArgumentError)
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:524:in `reload_type_map'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:166:in `clear_cache!'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:392:in `disconnect!'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:103:in `disconnect!'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `block (3 levels) in disconnect'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:433:in `each'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:433:in `block (2 levels) in disconnect'
        from /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:432:in `block in disconnect'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:676:in `block in with_exclusively_acquired_all_connections'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:751:in `with_new_connections_blocked'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:674:in `with_exclusively_acquired_all_connections'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:431:in `disconnect'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:453:in `disconnect!'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:991:in `each'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:991:in `clear_all_connections!'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_handling.rb:142:in `clear_all_connections!'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:588:in `block in load_schema_if_pending!'
        from /usr/lib/ruby/2.3.0/fileutils.rb:128:in `chdir'
        from /usr/lib/ruby/2.3.0/fileutils.rb:128:in `cd'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:586:in `load_schema_if_pending!'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:599:in `block in maintain_test_schema!'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:848:in `suppress_messages'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:604:in `method_missing'
        from /var/lib/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:599:in `maintain_test_schema!'
        from /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/test_help.rb:17:in `<main>'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
        from /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
        from /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
        from /home/ubuntu/projects/VisionBuilder/server/trunk/test/test_helper.rb:3:in `<main>'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
        from /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
        from /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
        from /home/ubuntu/projects/VisionBuilder/server/trunk/test/controllers/api/resources_controller_test.rb:1:in `<main>'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
        from /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
        from /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
        from /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/test_unit/runner.rb:50:in `block in load_tests'
        from /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/test_unit/runner.rb:50:in `each'
        from /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/test_unit/runner.rb:50:in `load_tests'
        from /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/test_unit/runner.rb:39:in `run'
        from /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/commands/test/test_command.rb:33:in `perform'
        from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
        from /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
        from /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
        from /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
        from /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
        from bin/rails:4:in `<main>'

**Comment by stadia** [comment]
#14
