### ISSUE TITLE
uninitialized constant ActiveRecord::ConnectionAdapters::Mysql2RgeoAdapter::INDEX_TYPES

### ISSUE THREAD

**Issue by adamkoperek-ttn** [stadia/activerecord-mysql2rgeo-adapter#11]
I'm getting this in `schema.rb` when migrating my db:

`# Could not dump table "xxxxx" because of following NameError`
`#   uninitialized constant ActiveRecord::ConnectionAdapters::Mysql2RgeoAdapter::INDEX_TYPES`

This are my `Gemfile` settings:

`gem 'mysql2', '~> 0.5.2'`
`gem 'rails', '~> 5.2.0'`
`gem 'rgeo', '1.0.0'`
`gem 'rgeo-activerecord', '~> 6.0.0'`
`gem 'activerecord-mysql2rgeo-adapter', '2.2.0'`

And I'm creating table column and index like this:

`t.point :point, null: false`
`t.index :point, type: :spatial`

**Comment by stadia** [comment]
deleted INDEX_TYPES at 5.2.0

**Comment by stadia** [comment]
#14
