### ISSUE TITLE
Version history doesn't match rubygems

### ISSUE THREAD

**Issue by rahul342** [stadia/activerecord-mysql2rgeo-adapter#18]
Hey @stadia, thanks for creating this! Would love to use this in our project. Few questions -

1. Is the gem stable, are you using and still maintaining this?
2. I noticed the version history listed here doesn't match the version history on https://rubygems.org/gems/activerecord-mysql2rgeo-adapter/versions. I am guessing the one here is from postgres one?
I am trying to use this on Rails 5.0, but it pulls a really old one v1.0.5. I couldn't figure out what have been the changes since. What do you recommend? Our codebase is fairly big so upgrading to 5.1 is a bit time consuming.

**Comment by stadia** [comment]
1. yes, i'm using this gem on production env.
