### ISSUE TITLE
`Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock'` error occurred on CircleCI

### ISSUE THREAD

**Issue by mono0926** [stadia/activerecord-mysql2rgeo-adapter#6]
This gem works fine on local environment, thanks.

But, when I run `rake db:create db:migrate` on CircleCI, it failed to connect to local MySQL server...
I couldn't resolve this error.

The error log is below:

<details><summary>CircleCI logs `rake db:create db:migrate`</summary>export RAILS_ENV="test"
export RACK_ENV="test"
bundle exec rake db:create db:migrate --trace
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.3-compliant syntax, but you are running 2.3.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:create
#<Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
Couldn't create database for {"database"=>"circle_ruby_test", "adapter"=>"mysql2rgeo", "pool"=>5, "charset"=>"utf8mb4", "encoding"=>"utf8mb4", "collation"=>"utf8mb4_general_ci", "username"=>"ubuntu", "socket"=>"/tmp/mysql.sock", "host"=>"localhost"}, {:charset=>"utf8mb4", :collation=>"utf8mb4_general_ci"}
(If you set the charset manually, make sure you have a matching collation)
Created database 'circle_ruby_test'
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config 
** Execute db:migrate
rake aborted!
Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:89:in `connect'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:89:in `initialize'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-mysql2rgeo-adapter-1.0.4/lib/active_record/connection_adapters/mysql2rgeo/create_connection.rb:38:in `new'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-mysql2rgeo-adapter-1.0.4/lib/active_record/connection_adapters/mysql2rgeo/create_connection.rb:38:in `mysql2rgeo_connection'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_handling.rb:91:in `connection'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/migration.rb:1100:in `initialize'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/migration.rb:1006:in `new'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/migration.rb:1006:in `up'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/migration.rb:984:in `migrate'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/opt/circleci/ruby/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
/home/ubuntu/joinus-black-server/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<top (required)>'
/opt/circleci/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/opt/circleci/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/circleci/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/opt/circleci/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/opt/circleci/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/circleci/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/circleci/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/opt/circleci/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/opt/circleci/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/opt/circleci/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/opt/circleci/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/opt/circleci/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/opt/circleci/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/opt/circleci/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `load'
/opt/circleci/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `<main>'
/opt/circleci/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/opt/circleci/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate

export RAILS_ENV="test"
export RACK_ENV="test"
bundle exec rake db:create db:migrate --trace
 returned exit code 1

Action failed: rake db:create db:migrate</details>

---

- activerecord-mysql2rgeo-adapter: v1.0.3
- Ruby: 2.3.0
- Rails: 5.0.1

**Comment by stadia** [comment]
i guess that's wrong settting at test environment.
because we are using this gem at production, all enviroment.
can u connect via socket on circle-ci? maybe you have to use tcp connecting

**Comment by mono0926** [comment]
> i guess that's wrong settting at test environment.
because we are using this gem at production, all enviroment.
can u connect via socket on circle-ci? maybe you have to use tcp connecting

Okay, thanks.
It seems that the error occurred due to my setting.
I'll continue to investigate.

But only this change occurred the error...

```diff
-  adapter: mysql2
+  adapter: mysql2rgeo
```

**Comment by stadia** [comment]
can i know project's link?

**Comment by mono0926** [comment]
> can i know project's link?

Sorry, the project's source code is private...

**Comment by mono0926** [comment]
I suspect that CircleCI's default MySQL version is old.
I'm investigating...

**Comment by mono0926** [comment]
> I suspect that CircleCI's default MySQL version is old.

This document and the log says MySQL version is 5.7.17, so version is okay.
[Ubuntu 14.04 (Trusty) - CircleCI](https://circleci.com/docs/1.0/build-image-trusty/#mysql)

**Comment by stadia** [comment]
current, that's result on TravisCI 
https://travis-ci.org/stadia/activerecord-mysql2rgeo-adapter/builds/221975851

all test is okay. and connected on mysql and execute sql command.

this is settings on test environment.
https://github.com/stadia/activerecord-mysql2rgeo-adapter/blob/master/test/database.yml

**Comment by mono0926** [comment]
I'm investigating and the error not resolved, but it seems that the problem is CircleCI's environment or configuration, so I close this.

Thanks!

**Comment by stadia** [comment]
Thanks!
